version : '3.1'

services:
    database: 
        build: Database
        ports:
            - "3306:3306"
        container_name: "database-container"
        restart: always

    backend:
        build: Backend
        ports: 
            - "3000:3000"
        container_name: back-container
        restart: always
        links:
            - database
        command : ["./wait-for-it.sh", "-t", "40", "database:3306", "--", "node", "app.js"]
        # above line does the following:
            # check periodically for 40 seconds if (host:port) = database:3306 is ready
            # if it is, run 'node app.js'
            # app.js is the file that is connecting with the db

    frontend: 
        build: quiz-app
        ports:
            - "4200:4200"
        container_name: front-container
        restart: always
