version : '2'

services:
    frontend: 
        build: quiz-app
        ports:
            - "4200:4200"
        container_name: front-container
        restart: always

    backend:
        build: backend
        ports: 
            - "3000:3000"
        container_name: back-container
        restart: always
        links: 
            - database
    
    database: 
        build: DatabaseScripts
        container_name: "database-container"
        restart: always
